### ISSUE TITLE
块分类不够合理 / Block classification isn't reasonable enough

### ISSUE THREAD

**Issue by SquareCM2** [A4-Tacks/blockly_for_mindustry_logic_bang_lang#1]
现在的块仅分为Bang，Value，Logic三类，并且逻辑块过于杂乱（数据框开会
建议将Logic分区里的块功能拆开，并且增加Unit、Block等分区，类似下图：
![Snipaste_2024-01-01_20-13-40](https://github.com/A4-Tacks/blockly_for_mindustry_logic_bang_lang/assets/155364934/28045d8a-3f59-4d01-bc6d-de090c9767a7)

（不够合理，仅作参考）

**Comment by A4-Tacks** [comment]
好的，过会我会将其细分一下，这非常简单

**Comment by A4-Tacks** [comment]
将工具箱中的语句分到了多个类中, 详见 [51e9ef0]

[51e9ef0]: https://github.com/A4-Tacks/blockly_for_mindustry_logic_bang_lang/commit/51e9ef01cbc186fb862aabdcb48c36ae48318de8

**Comment by A4-Tacks** [comment]
我是否将此 issue 关闭？
还是继续修改实际语句颜色与逻辑语句对应？

**Comment by SquareCM2** [comment]
> 我是否将此 issue 关闭？ 还是继续修改实际语句颜色与逻辑语句对应？

建议继续修改实际语句颜色
另外我注意到项目好像没有专门的数值块，请问是怎么回事

**Comment by SquareCM2** [comment]
并且我的设想是将逻辑块进行**功能上的**拆分
况且就按现在这个样子
![image](https://github.com/A4-Tacks/blockly_for_mindustry_logic_bang_lang/assets/155364934/a2e246d5-d300-4c36-8285-6cef22022e24)
不说令人茫然，至少也是不知所措了。
建议如本issue开头的图片一样进行**功能拆分**。

**Comment by A4-Tacks** [comment]
> > 我是否将此 issue 关闭？ 还是继续修改实际语句颜色与逻辑语句对应？
> 
> 建议继续修改实际语句颜色 另外我注意到项目好像没有专门的数值块，请问是怎么回事

你需要考虑一点：这个是将代码生成到Bang语言的，而不是逻辑，所以设计上是直接考虑Bang语言的。
数值直接使用Var块编写 其包含了变量常量数值环境变量等


> 并且我的设想是将逻辑块进行**功能上的**拆分 况且就按现在这个样子 image 不说令人茫然，至少也是不知所措了。 建议如本issue开头的图片一样进行**功能拆分**。

同上述描述，所有逻辑语句都是生成Bang语言中的Other语法，所以是这么设计。
并且如逻辑风格在一行中进行编写

**Comment by A4-Tacks** [comment]
颜色已经完成，详见 [9e1e65d]。
所以我把issue关了？

[9e1e65d]: https://github.com/A4-Tacks/blockly_for_mindustry_logic_bang_lang/commit/9e1e65d33bc7e733b8c743b98cdc13c9b505e05b
